# Generated by Django 4.0.2 on 2022-02-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_item_supplier_item_quantity_alter_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=254, null=True)),
                ('lastName', models.CharField(max_length=1000, null=True)),
                ('emailAddress', models.CharField(max_length=254, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=254, null=True)),
                ('lastName', models.CharField(max_length=1000, null=True)),
                ('emailAddress', models.CharField(max_length=254, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=254, null=True)),
                ('telNo', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=254, null=True)),
                ('country', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
