# Generated by Django 4.0.2 on 2022-02-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_admin_destination_user_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, null=True)),
                ('destinationName', models.CharField(max_length=100, null=True)),
                ('review', models.TextField(max_length=3000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
