# Generated by Django 4.0.2 on 2022-02-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_reviews_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
