# Generated by Django 4.0.2 on 2022-02-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_review_date_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='destinationName',
        ),
        migrations.RemoveField(
            model_name='review',
            name='userName',
        ),
        migrations.AddField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.destination'),
        ),
    ]
