# Generated by Django 4.0.2 on 2022-02-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
